-- ============================================================================
-- Back-office /admin — écriture sécurisée (Hadith) — Supabase Auth
-- ============================================================================
-- Règle admin : seul le compte connecté dont l'e-mail == l'admin peut écrire.
create or replace function public.is_admin() returns boolean language sql stable as $$
  select coalesce(lower(auth.jwt() ->> 'email'), '') = 'karimromdhane7@gmail.com'
$$;
-- Politiques d'écriture (INSERT/UPDATE/DELETE) réservées à l'admin sur
-- hadiths, hadith_sources, narrateurs, recueils, hadith_themes (SELECT reste public).
--   create policy "admin insert" on public.<t> for insert to authenticated with check (public.is_admin());
--   create policy "admin update" on public.<t> for update to authenticated using (public.is_admin()) with check (public.is_admin());
--   create policy "admin delete" on public.<t> for delete to authenticated using (public.is_admin());
--
-- RPC :
--   admin_get_hadith(id)   → colonnes brutes + sources + tag (lecture pour édition)
--   themes_for_tag(tag)    → aperçu des thèmes déduits d'un CSV de tags
--   admin_save_hadith(p jsonb) SECURITY DEFINER, gardé par is_admin() :
--     enregistre en une transaction le hadith (+ statut/slug), un narrateur
--     éventuellement nouveau, remplace les hadith_sources (recueil existant ou
--     nouveau) et re-déduit les hadith_themes depuis les tags. Retourne l'id.
--   grant execute admin_save_hadith → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Paroles (même patron que Hadith)
-- ─────────────────────────────────────────────────────────────────────────
-- RLS écriture admin sur paroles, parole_images, parole_themes, savants.
-- admin_get_parole(id) → colonnes brutes + images + savant_id + tag.
-- admin_save_parole(p jsonb) SECURITY DEFINER, gardé is_admin() : parole
-- (+ slug), savant éventuellement nouveau, remplace parole_images (scans),
-- re-déduit parole_themes depuis les tags. grant → authenticated.
-- Datalist rapporteur (front) alimenté par hadith_rubriques().rapporteurs.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Versets / hadiths équivoques (entité parent + 3 enfants)
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations : admin_equivoques_rls, admin_equivoques_rpcs.
-- RLS écriture admin (insert/update/delete, is_admin()) sur :
--   versets_equivoques, verset_preuves, verset_images, verset_lies.
--   (lecture : « Public read » existante conservée).
-- admin_get_verset_equivoque(id) → colonnes brutes + preuves[]
--   (type, ref_id, contenu_libre, ordre) + images[] + lies[] (verset_lie_id).
-- admin_list_verset_refs() SECURITY DEFINER, gardé is_admin() : renvoie
--   { hadiths, paroles, versets } (id + label) pour les sélecteurs de preuves
--   et de liens (inclut les non-publiés).
-- admin_save_verset_equivoque(p jsonb) SECURITY DEFINER, gardé is_admin() :
--   upsert du parent (slug généré à la création, sourate='' tolérée pour un
--   hadith équivoque), puis remplacement complet des preuves (coran→contenu
--   libre ; hadith/parole→ref_id), des images (alt défaut « Scan du livre »)
--   et des liens verset_lies (anti-auto-référence + on conflict do nothing).
--   Retourne l'id. grant execute → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran thématique (table `coran` + coran_themes)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_coran_rpcs.
-- RLS écriture admin sur coran, coran_themes (lecture publique conservée).
-- admin_get_coran(id) → colonnes brutes + tag.
-- admin_save_coran(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert du
--   verset thématique (le trigger set_arabe_hash renseigne arabe_hash ; l'index
--   uniq_coran_arabe_hash détecte les doublons), puis re-déduit coran_themes
--   depuis les tags (mapping theme_tags). grant → authenticated.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran, exégèse (sourates -> versets -> exégèses)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_sourates_rpcs.
-- RLS écriture admin sur sourates, versets, exegeses (lecture publique conservée).
-- admin_get_sourate(id) → sourate + versets[] (chacun avec ses exegeses[]).
-- admin_list_sourates() → liste (numero, nom, slug, nb de versets saisis).
-- admin_save_sourate(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert de
--   la sourate (slug généré à la création ; numero unique), puis remplacement
--   complet des versets (delete cascade => exégèses) et ré-insertion des versets
--   et de leurs exégèses (ordre recalculé). Éditeur imbriqué côté admin.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Invocations & Évocations (table `invocations`)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_invocations_rpcs.
-- Table live unifiée (type_id 1=invocation/duʿāʾ, 2=évocation/dhikr) ;
-- douaas/dhikrs = tables sources héritées, non éditées ici.
-- RLS écriture admin sur invocations (lecture publique conservée).
-- admin_get_invocation(id) → colonnes brutes.
-- admin_save_invocation(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert
--   (id = identity BY DEFAULT). Pas de slug, pas de mapping thèmes.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Savants (fiche complète)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_savants_rpcs.
-- Complète la création minimale (nom+slug) faite à la volée par admin_save_parole.
-- RLS écriture admin sur savants (recréées, idempotent).
-- admin_get_savant(id) → nom, nom_arabe, slug, ecole_id, generation, naissance,
--   deces, resume, biographie, domaines (text[]).
-- admin_save_savant(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert
--   (id = identity ALWAYS => jamais fourni). slug généré à la création ;
--   generation contrainte (sahabi|salaf|tabii|tabi_tabii|khalaf) ; domaines
--   converti depuis un tableau JSON ; resume_auto/generation_a_verifier=false
--   (saisie manuelle par l'auteur).

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Dossiers thématiques (parent + preuves/images/liens)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_dossiers_rpcs.
-- RLS écriture admin sur dossiers, dossier_preuves, dossier_images, dossiers_lies.
-- admin_get_dossier(id) → colonnes (h1, meta, croyance/objection/réponse, published)
--   + preuves[] (type hadith|parole|verset, ref_id, ordre) + images[] + lies[].
-- admin_list_dossiers() / admin_list_dossier_refs() (hadiths/paroles/versets=coran),
--   SECURITY DEFINER gardés is_admin().
-- admin_save_dossier(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert (slug
--   généré à la création) + remplacement complet preuves/images/liens.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Exposés (page Markdown clé=slug + citations)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_exposes_rpcs.
-- RLS écriture admin sur exposes, expose_citations.
-- admin_get_expose(slug) → page (titre, contenu_md, verset d'en-tête) + citations[]
--   (section, type verset|hadith|parole, ref_id, arabe/phonetique/signification/ref,
--    accordeon, ordre).
-- admin_list_exposes() / admin_list_expose_refs() (hadiths/paroles), SECURITY DEFINER.
-- admin_save_expose(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert par slug
--   (on conflict) + remplacement complet des citations. Retourne le slug.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Fiqh & La femme musulmane (tables plates par chapitre)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_fiqh_femmes_rpcs.
-- RLS écriture admin sur fiqh, femmes (lecture publique conservée).
-- Édition par ligne (le regroupement par chapitre se fait à la lecture via
-- fiqh_by_ecole / femmes_all). id = identity ALWAYS => jamais fourni.
-- admin_get_fiqh(id)/admin_save_fiqh(p) : ecole (Hanafi|Malikite|Shafii|Hanbalite)
--   + chapitre obligatoires ; sujet, type, texte (md), texte_arabe, source, tag, ordre.
-- admin_get_femme(id)/admin_save_femme(p) : chapitre obligatoire ; matn, commentaire,
--   texte_arabe, source, ordre. SECURITY DEFINER, gardés is_admin().

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 3.2 — Contenu composable (table contenu_blocs)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase3_contenu_blocs.
-- Un article = suite de blocs ordonnés (texte | commentaire | preuve).
-- parent_id TEXT (polymorphe : id bigint-as-text ou slug d'exposé) — pas de FK.
-- Règle clé : un bloc preuve NE COPIE PAS le texte ; il pointe (citation_type,
--   citation_id) et le rendu lit la source en direct → correction unique
--   répercutée partout.
-- RLS : lecture publique ; écriture admin (is_admin()).
-- get_blocs(parent_type,parent_id) [public] : blocs ordonnés, preuves résolues
--   depuis hadiths/paroles/coran (+ source_rubrique).
-- admin_get_blocs / admin_save_blocs (SECURITY DEFINER, remplacement complet).
-- Sélecteur de preuves réutilise admin_list_dossier_refs (hadiths/paroles/coran).

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.6 — Suppression admin avec garde-fou de dépendances
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase4_admin_delete.
-- admin_entry_dependencies(kind,id) : où une source citable (hadith/parole/
--   verset=coran) est référencée comme preuve (contenu_blocs, verset_preuves,
--   dossier_preuves, expose_citations, attribut_citations).
-- admin_delete_entry({kind,id,force}) SECURITY DEFINER, is_admin() :
--   refuse si référencée (sauf force → retire aussi les références) ; supprime
--   les blocs d'article dont l'entrée est parent ; refuse un savant ayant des
--   paroles ; s'appuie sur les FK ON DELETE CASCADE pour les enfants.
-- UI : DeleteEntryButton (confirmation « supprimer », liste des dépendances,
--   option forcer) câblé dans les 12 formulaires admin (mode édition).

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.1 — Paroles qui rapportent / commentent
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations : phase4_paroles_rapporteur_commente, phase4_paroles_rpcs_update.
-- paroles.rapporteur_savant_id (FK savants) + commente_parole_id (self-FK),
-- nullable, ON DELETE SET NULL. savant_id reste l'AUTEUR des mots.
-- get_parole expose rapporteur {nom,slug} + commente {sujet,slug} ;
-- admin_get_parole/admin_save_parole gèrent les deux liens.

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.7 — « Dossiers liés » automatiques par thème partagé
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase4_related_by_theme.
-- related_by_theme(kind,id,limit) [public] : autres contenus (hadith/parole/
--   verset) partageant au moins un thème avec l'entrée, dédupliqués. UI :
--   composant RelatedByTheme sur les fiches Hadith et Parole (« Sur le même
--   thème »). Plus aucune sélection manuelle.
