-- ============================================================================
-- Back-office /admin — écriture sécurisée (Hadith) — Supabase Auth
-- ============================================================================
-- Règle admin : seul le compte connecté dont l'e-mail == l'admin peut écrire.
create or replace function public.is_admin() returns boolean language sql stable as $$
  select coalesce(lower(auth.jwt() ->> 'email'), '') = 'karimromdhane7@gmail.com'
$$;
-- Politiques d'écriture (INSERT/UPDATE/DELETE) réservées à l'admin sur
-- hadiths, hadith_sources, narrateurs, recueils, hadith_themes (SELECT reste public).
--   create policy "admin insert" on public.<t> for insert to authenticated with check (public.is_admin());
--   create policy "admin update" on public.<t> for update to authenticated using (public.is_admin()) with check (public.is_admin());
--   create policy "admin delete" on public.<t> for delete to authenticated using (public.is_admin());
--
-- RPC :
--   admin_get_hadith(id)   → colonnes brutes + sources + tag (lecture pour édition)
--   themes_for_tag(tag)    → aperçu des thèmes déduits d'un CSV de tags
--   admin_save_hadith(p jsonb) SECURITY DEFINER, gardé par is_admin() :
--     enregistre en une transaction le hadith (+ statut/slug), un narrateur
--     éventuellement nouveau, remplace les hadith_sources (recueil existant ou
--     nouveau) et re-déduit les hadith_themes depuis les tags. Retourne l'id.
--   grant execute admin_save_hadith → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Paroles (même patron que Hadith)
-- ─────────────────────────────────────────────────────────────────────────
-- RLS écriture admin sur paroles, parole_images, parole_themes, savants.
-- admin_get_parole(id) → colonnes brutes + images + savant_id + tag.
-- admin_save_parole(p jsonb) SECURITY DEFINER, gardé is_admin() : parole
-- (+ slug), savant éventuellement nouveau, remplace parole_images (scans),
-- re-déduit parole_themes depuis les tags. grant → authenticated.
-- Datalist rapporteur (front) alimenté par hadith_rubriques().rapporteurs.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Versets / hadiths équivoques (entité parent + 3 enfants)
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations : admin_equivoques_rls, admin_equivoques_rpcs.
-- RLS écriture admin (insert/update/delete, is_admin()) sur :
--   versets_equivoques, verset_preuves, verset_images, verset_lies.
--   (lecture : « Public read » existante conservée).
-- admin_get_verset_equivoque(id) → colonnes brutes + preuves[]
--   (type, ref_id, contenu_libre, ordre) + images[] + lies[] (verset_lie_id).
-- admin_list_verset_refs() SECURITY DEFINER, gardé is_admin() : renvoie
--   { hadiths, paroles, versets } (id + label) pour les sélecteurs de preuves
--   et de liens (inclut les non-publiés).
-- admin_save_verset_equivoque(p jsonb) SECURITY DEFINER, gardé is_admin() :
--   upsert du parent (slug généré à la création, sourate='' tolérée pour un
--   hadith équivoque), puis remplacement complet des preuves (coran→contenu
--   libre ; hadith/parole→ref_id), des images (alt défaut « Scan du livre »)
--   et des liens verset_lies (anti-auto-référence + on conflict do nothing).
--   Retourne l'id. grant execute → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran thématique (table `coran` + coran_themes)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_coran_rpcs.
-- RLS écriture admin sur coran, coran_themes (lecture publique conservée).
-- admin_get_coran(id) → colonnes brutes + tag.
-- admin_save_coran(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert du
--   verset thématique (le trigger set_arabe_hash renseigne arabe_hash ; l'index
--   uniq_coran_arabe_hash détecte les doublons), puis re-déduit coran_themes
--   depuis les tags (mapping theme_tags). grant → authenticated.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran, exégèse (sourates -> versets -> exégèses)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_sourates_rpcs.
-- RLS écriture admin sur sourates, versets, exegeses (lecture publique conservée).
-- admin_get_sourate(id) → sourate + versets[] (chacun avec ses exegeses[]).
-- admin_list_sourates() → liste (numero, nom, slug, nb de versets saisis).
-- admin_save_sourate(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert de
--   la sourate (slug généré à la création ; numero unique), puis remplacement
--   complet des versets (delete cascade => exégèses) et ré-insertion des versets
--   et de leurs exégèses (ordre recalculé). Éditeur imbriqué côté admin.
