-- ============================================================================
-- Back-office /admin — écriture sécurisée (Hadith) — Supabase Auth
-- ============================================================================
-- Règle admin : seul le compte connecté dont l'e-mail == l'admin peut écrire.
create or replace function public.is_admin() returns boolean language sql stable as $$
  select coalesce(lower(auth.jwt() ->> 'email'), '') = 'karimromdhane7@gmail.com'
$$;
-- Politiques d'écriture (INSERT/UPDATE/DELETE) réservées à l'admin sur
-- hadiths, hadith_sources, narrateurs, recueils, hadith_themes (SELECT reste public).
--   create policy "admin insert" on public.<t> for insert to authenticated with check (public.is_admin());
--   create policy "admin update" on public.<t> for update to authenticated using (public.is_admin()) with check (public.is_admin());
--   create policy "admin delete" on public.<t> for delete to authenticated using (public.is_admin());
--
-- RPC :
--   admin_get_hadith(id)   → colonnes brutes + sources + tag (lecture pour édition)
--   themes_for_tag(tag)    → aperçu des thèmes déduits d'un CSV de tags
--   admin_save_hadith(p jsonb) SECURITY DEFINER, gardé par is_admin() :
--     enregistre en une transaction le hadith (+ statut/slug), un narrateur
--     éventuellement nouveau, remplace les hadith_sources (recueil existant ou
--     nouveau) et re-déduit les hadith_themes depuis les tags. Retourne l'id.
--   grant execute admin_save_hadith → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Paroles (même patron que Hadith)
-- ─────────────────────────────────────────────────────────────────────────
-- RLS écriture admin sur paroles, parole_images, parole_themes, savants.
-- admin_get_parole(id) → colonnes brutes + images + savant_id + tag.
-- admin_save_parole(p jsonb) SECURITY DEFINER, gardé is_admin() : parole
-- (+ slug), savant éventuellement nouveau, remplace parole_images (scans),
-- re-déduit parole_themes depuis les tags. grant → authenticated.
-- Datalist rapporteur (front) alimenté par hadith_rubriques().rapporteurs.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Versets / hadiths équivoques (entité parent + 3 enfants)
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations : admin_equivoques_rls, admin_equivoques_rpcs.
-- RLS écriture admin (insert/update/delete, is_admin()) sur :
--   versets_equivoques, verset_preuves, verset_images, verset_lies.
--   (lecture : « Public read » existante conservée).
-- admin_get_verset_equivoque(id) → colonnes brutes + preuves[]
--   (type, ref_id, contenu_libre, ordre) + images[] + lies[] (verset_lie_id).
-- admin_list_verset_refs() SECURITY DEFINER, gardé is_admin() : renvoie
--   { hadiths, paroles, versets } (id + label) pour les sélecteurs de preuves
--   et de liens (inclut les non-publiés).
-- admin_save_verset_equivoque(p jsonb) SECURITY DEFINER, gardé is_admin() :
--   upsert du parent (slug généré à la création, sourate='' tolérée pour un
--   hadith équivoque), puis remplacement complet des preuves (coran→contenu
--   libre ; hadith/parole→ref_id), des images (alt défaut « Scan du livre »)
--   et des liens verset_lies (anti-auto-référence + on conflict do nothing).
--   Retourne l'id. grant execute → authenticated seulement.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran thématique (table `coran` + coran_themes)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_coran_rpcs.
-- RLS écriture admin sur coran, coran_themes (lecture publique conservée).
-- admin_get_coran(id) → colonnes brutes + tag.
-- admin_save_coran(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert du
--   verset thématique (le trigger set_arabe_hash renseigne arabe_hash ; l'index
--   uniq_coran_arabe_hash détecte les doublons), puis re-déduit coran_themes
--   depuis les tags (mapping theme_tags). grant → authenticated.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Coran, exégèse (sourates -> versets -> exégèses)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_sourates_rpcs.
-- RLS écriture admin sur sourates, versets, exegeses (lecture publique conservée).
-- admin_get_sourate(id) → sourate + versets[] (chacun avec ses exegeses[]).
-- admin_list_sourates() → liste (numero, nom, slug, nb de versets saisis).
-- admin_save_sourate(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert de
--   la sourate (slug généré à la création ; numero unique), puis remplacement
--   complet des versets (delete cascade => exégèses) et ré-insertion des versets
--   et de leurs exégèses (ordre recalculé). Éditeur imbriqué côté admin.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Invocations & Évocations (table `invocations`)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_invocations_rpcs.
-- Table live unifiée (type_id 1=invocation/duʿāʾ, 2=évocation/dhikr) ;
-- douaas/dhikrs = tables sources héritées, non éditées ici.
-- RLS écriture admin sur invocations (lecture publique conservée).
-- admin_get_invocation(id) → colonnes brutes.
-- admin_save_invocation(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert
--   (id = identity BY DEFAULT). Pas de slug, pas de mapping thèmes.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Savants (fiche complète)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_savants_rpcs.
-- Complète la création minimale (nom+slug) faite à la volée par admin_save_parole.
-- RLS écriture admin sur savants (recréées, idempotent).
-- admin_get_savant(id) → nom, nom_arabe, slug, ecole_id, generation, naissance,
--   deces, resume, biographie, domaines (text[]).
-- admin_save_savant(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert
--   (id = identity ALWAYS => jamais fourni). slug généré à la création ;
--   generation contrainte (sahabi|salaf|tabii|tabi_tabii|khalaf) ; domaines
--   converti depuis un tableau JSON ; resume_auto/generation_a_verifier=false
--   (saisie manuelle par l'auteur).

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Dossiers thématiques (parent + preuves/images/liens)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_dossiers_rpcs.
-- RLS écriture admin sur dossiers, dossier_preuves, dossier_images, dossiers_lies.
-- admin_get_dossier(id) → colonnes (h1, meta, croyance/objection/réponse, published)
--   + preuves[] (type hadith|parole|verset, ref_id, ordre) + images[] + lies[].
-- admin_list_dossiers() / admin_list_dossier_refs() (hadiths/paroles/versets=coran),
--   SECURITY DEFINER gardés is_admin().
-- admin_save_dossier(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert (slug
--   généré à la création) + remplacement complet preuves/images/liens.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Exposés (page Markdown clé=slug + citations)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_exposes_rpcs.
-- RLS écriture admin sur exposes, expose_citations.
-- admin_get_expose(slug) → page (titre, contenu_md, verset d'en-tête) + citations[]
--   (section, type verset|hadith|parole, ref_id, arabe/phonetique/signification/ref,
--    accordeon, ordre).
-- admin_list_exposes() / admin_list_expose_refs() (hadiths/paroles), SECURITY DEFINER.
-- admin_save_expose(p jsonb) SECURITY DEFINER, gardé is_admin() : upsert par slug
--   (on conflict) + remplacement complet des citations. Retourne le slug.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Fiqh & La femme musulmane (tables plates par chapitre)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_fiqh_femmes_rpcs.
-- RLS écriture admin sur fiqh, femmes (lecture publique conservée).
-- Édition par ligne (le regroupement par chapitre se fait à la lecture via
-- fiqh_by_ecole / femmes_all). id = identity ALWAYS => jamais fourni.
-- admin_get_fiqh(id)/admin_save_fiqh(p) : ecole (Hanafi|Malikite|Shafii|Hanbalite)
--   + chapitre obligatoires ; sujet, type, texte (md), texte_arabe, source, tag, ordre.
-- admin_get_femme(id)/admin_save_femme(p) : chapitre obligatoire ; matn, commentaire,
--   texte_arabe, source, ordre. SECURITY DEFINER, gardés is_admin().

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 3.2 — Contenu composable (table contenu_blocs)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase3_contenu_blocs.
-- Un article = suite de blocs ordonnés (texte | commentaire | preuve).
-- parent_id TEXT (polymorphe : id bigint-as-text ou slug d'exposé) — pas de FK.
-- Règle clé : un bloc preuve NE COPIE PAS le texte ; il pointe (citation_type,
--   citation_id) et le rendu lit la source en direct → correction unique
--   répercutée partout.
-- RLS : lecture publique ; écriture admin (is_admin()).
-- get_blocs(parent_type,parent_id) [public] : blocs ordonnés, preuves résolues
--   depuis hadiths/paroles/coran (+ source_rubrique).
-- admin_get_blocs / admin_save_blocs (SECURITY DEFINER, remplacement complet).
-- Sélecteur de preuves réutilise admin_list_dossier_refs (hadiths/paroles/coran).

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.6 — Suppression admin avec garde-fou de dépendances
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase4_admin_delete.
-- admin_entry_dependencies(kind,id) : où une source citable (hadith/parole/
--   verset=coran) est référencée comme preuve (contenu_blocs, verset_preuves,
--   dossier_preuves, expose_citations, attribut_citations).
-- admin_delete_entry({kind,id,force}) SECURITY DEFINER, is_admin() :
--   refuse si référencée (sauf force → retire aussi les références) ; supprime
--   les blocs d'article dont l'entrée est parent ; refuse un savant ayant des
--   paroles ; s'appuie sur les FK ON DELETE CASCADE pour les enfants.
-- UI : DeleteEntryButton (confirmation « supprimer », liste des dépendances,
--   option forcer) câblé dans les 12 formulaires admin (mode édition).

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.1 — Paroles qui rapportent / commentent
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations : phase4_paroles_rapporteur_commente, phase4_paroles_rpcs_update.
-- paroles.rapporteur_savant_id (FK savants) + commente_parole_id (self-FK),
-- nullable, ON DELETE SET NULL. savant_id reste l'AUTEUR des mots.
-- get_parole expose rapporteur {nom,slug} + commente {sujet,slug} ;
-- admin_get_parole/admin_save_parole gèrent les deux liens.

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.7 — « Dossiers liés » automatiques par thème partagé
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase4_related_by_theme.
-- related_by_theme(kind,id,limit) [public] : autres contenus (hadith/parole/
--   verset) partageant au moins un thème avec l'entrée, dédupliqués. UI :
--   composant RelatedByTheme sur les fiches Hadith et Parole (« Sur le même
--   thème »). Plus aucune sélection manuelle.

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 4.4 — Recherche globale unifiée
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase4_search_all.
-- search_all(q, limit) [public] : FTS français (to_tsvector/websearch_to_tsquery
--   + ts_rank) avec repli unaccent+ilike (translittération), sur hadiths,
--   paroles, invocations, versets (coran) et thèmes. Résultats groupés.
-- UI : page /recherche (débouncée, ?q= dans l'URL) + icône loupe dans la nav.
-- (Exposés exclus : pas de route publique générique → à traiter en 4.5.)

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 5.1 — Récits hiérarchisés (modèle)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase5_recits_hierarchie.
-- recits.parent_recit_id (self-FK, ON DELETE SET NULL) + index (parent, ordre).
-- Additif : aucun rattachement appliqué. Proposition dans
-- docs/proposition-phase5-recits.md (à valider par l'auteur avant peuplement).
--
-- Phase 4.5 — audit admin→public : docs/rapport-audit-4.5.md
--   (istawā non publié = placeholder ; exposés = pas de route générique).

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 5 (Option A) — récits hiérarchisés : peuplement + RPCs
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase5_recits_rpcs (+ data : 6 bio-parents créés, épisodes
-- rattachés : Ibrāhīm←9,13 ; Mūsā←11 ; ʿĪsā←10 ; Sulaymān←7 ; Yūnus←8 ;
-- Muḥammad ﷺ←14).
-- recits_all : n'expose que les parents (parent_recit_id IS NULL) + nb_enfants.
-- get_recit : ajoute enfants[] (« Ses récits »). Admin : sélecteur de récit
-- parent (créer un parent = laisser vide ; rattacher = choisir le parent).

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — Recherche d'occurrences → correction directe
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : admin_search_occurrences.
-- admin_search_occurrences(q, limit) SECURITY DEFINER, is_admin() : balaie les
--   textes de TOUTES les rubriques (hadiths, paroles, coran, invocations,
--   équivoques, dossiers, exposés, récits, fiqh, femmes, savants, blocs
--   d'article) en insensible casse+accents, renvoie {kind, ref, label, extrait,
--   path admin}. Sert à homogénéiser les graphies (« Al-Boukhari » vs
--   « Al-Bukhari »). admin_snip = extrait centré sur l'occurrence.
-- UI : page /admin/recherche (surlignage, lien vers le formulaire d'édition) +
--   entrée « Recherche & correction » dans le menu admin.

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 3.5/3.6 — bascule des équivoques vers les blocs (un seul moteur)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration : phase3_migrate_equivoques_to_blocs (idempotent, non destructif).
-- Génère contenu_blocs depuis le triptyque existant (sens_juste → texte ;
-- verset_preuves coran(contenu_libre) → texte, hadith/parole(ref) → preuve ;
-- objection → texte ; reponse → texte) pour les équivoques SANS blocs.
-- Colonnes conservées (rien supprimé).
-- Rendu public : la fiche équivoque privilégie les blocs quand ils existent
-- (triptyque + sommaire legacy masqués), sinon repli sur l'ancien rendu.
-- Admin : note indiquant que la section 3 (ancien format) est ignorée dès
-- qu'un article composable (section 8) existe.

-- ─────────────────────────────────────────────────────────────────────────
-- Nettoyage istiwā + bascule des dossiers vers les blocs
-- ─────────────────────────────────────────────────────────────────────────
-- Suppression de l'équivoque placeholder « istiwa-sur-le-trone » (démo non
--   publiée, doublon du dossier « le-sens-de-l-istiwa ») via admin_delete_entry.
-- Migration migrate_dossiers_to_blocs (idempotente, non destructive) : triptyque
--   dossier (croyance / preuves / objection / réponse) → contenu_blocs.
-- Page /dossiers/:slug : privilégie les blocs quand ils existent (repli legacy).
-- Admin dossier : éditeur de blocs (section 7).

-- ─────────────────────────────────────────────────────────────────────────
-- Hadiths — rapporteurs & narrateurs individuels (filtrage + saisie multiple)
-- ─────────────────────────────────────────────────────────────────────────
-- Constat : hadiths.rapporteur / hadiths.narrateur sont des TEXTES agrégés
--   (« Abou Dawoud, Ahmad Ibn Hanbal, At-Tirmidhi ») régénérés par les triggers
--   sync_hadith_rapporteurs / sync_hadith_narrateurs depuis les tables de
--   liaison (source de vérité) hadith_rapporteurs / hadith_narrateurs.
--   Côté public le filtre proposait ces chaînes agrégées → impossible de
--   filtrer par « Al-Bukhari » seul ; côté admin la saisie était mono-valeur
--   (datalist rapporteur + select narrateur).
--
-- Migration : hadith_filters_by_individual
--   hadith_rubriques() : rapporteurs = DISTINCT savants.nom via hadith_rapporteurs ;
--     narrateurs = DISTINCT narrateurs.nom via hadith_narrateurs (noms unitaires).
--   search_hadiths() : rapporteur_filter / narrateur_filter deviennent des
--     EXISTS sur les liaisons (match d'UN nom exact), plus d'ilike sur l'agrégat.
--     Génération / rôle / sexe du narrateur pris sur la 1re liaison (order n.id).
--   → aucun changement front : la page Hadiths consomme ces RPCs directement.
--
-- Migration : admin_hadith_multi_rapporteurs
--   admin_get_hadith(id) : renvoie en plus rapporteur_ids[] (hadith_rapporteurs)
--     et narrateur_ids[] (hadith_narrateurs).
--   admin_save_hadith(p) : accepte rapporteur_ids[] / narrateur_ids[] ;
--     new_narrateur (facultatif) crée le Compagnon (on conflict nom) et l'ajoute.
--     Les liaisons sont remplacées (delete + insert filtré sur l'existence) ;
--     le texte rapporteur/narrateur est laissé au trigger (mis à null à l'écriture
--     quand des ids sont fournis). Sources & thèmes inchangés.
-- Admin (front) : section 3 « Narrateurs & rapporteurs » = deux sélecteurs
--   multiples avec recherche (puces retirables). Rapporteurs = savants ;
--   narrateurs = Compagnons + création d'un nouveau narrateur. AdminService :
--   HadithFormData / HadithEditShape portent rapporteur_ids[] / narrateur_ids[].

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — recherche d'occurrences insensible aux diacritiques arabes
-- ─────────────────────────────────────────────────────────────────────────
-- Symptôme : un texte arabe rejeté comme doublon à la saisie (arabe_hash)
--   restait introuvable dans « Recherche & correction ». Deux causes dans
--   admin_search_occurrences : (1) texte_arabe (et colonnes arabes) absents du
--   champ de recherche des hadiths ; (2) matching via unaccent() (latin) qui ne
--   retire pas les harakât — une graphie vocalisée différemment ne matche pas.
-- Migration : admin_search_occurrences_arabic.
--   Ajout d'un second motif pat_ar = '%'||normalize_ar(q)||'%' et, pour chaque
--   rubrique, d'un OR normalize_ar(<colonnes arabes>) like pat_ar (même
--   normalisation que arabe_hash : hamza unifiée, harakât/tatwil/guillemets
--   retirés, espaces compactés). Les colonnes arabes sont aussi ajoutées aux
--   extraits. Le motif latin existant est conservé (recherche FR inchangée).

-- ─────────────────────────────────────────────────────────────────────────
-- Recherche par liste (barres de recherche) insensible aux harakât — suite
-- ─────────────────────────────────────────────────────────────────────────
-- search_hadiths / search_paroles intégraient déjà normalize_ar(texte_arabe).
-- Migration : search_arabic_normalize_coran_invocations — même clause ajoutée à
--   search_coran, search_invocations, search_dhikrs, search_douaas :
--   « or normalize_ar(texte_arabe) ilike '%'||normalize_ar(q)||'%' ».
--   Toutes les barres de recherche admin retrouvent désormais un texte arabe
--   quelle que soit sa vocalisation (harakât, hamza). Aucun changement front.

-- ─────────────────────────────────────────────────────────────────────────
-- Compagnons (narrateurs) → présents aussi dans la table savants
-- ─────────────────────────────────────────────────────────────────────────
-- Besoin : les compagnons présents uniquement dans `narrateurs` doivent
--   exister comme fiches `savants` (liste admin, sélection comme rapporteur…).
-- Migration : narrateurs_sync_to_savants.
--   • Fonction sync_narrateur_to_savant() + trigger trg_sync_narrateur_to_savant
--     AFTER INSERT OR UPDATE OF nom, generation ON narrateurs :
--     crée la fiche savant (generation 'sahabi', domaines {Compagnon}, slug
--     unique dérivé du nom) si absente ; répercute un renommage (si le nouveau
--     nom est libre). NON destructif : aucune suppression automatique.
--   • Backfill des compagnons existants absents de savants (40 fiches créées).
-- Affichage : la liste admin (lecture directe de la table) les montre aussitôt ;
--   la page publique savants_all() ne liste que les savants AVEC biographie, donc
--   ces fiches n'apparaissent en public qu'une fois une bio saisie.
-- NB data : `narrateurs` contient un doublon interne (Abou Saʿid al-Khudri, ids
--   8 et 14, graphies différentes) — à fusionner manuellement si souhaité.

-- ─────────────────────────────────────────────────────────────────────────
-- Fusion du doublon narrateur « Abou Saʿid al-Khudri »
-- ─────────────────────────────────────────────────────────────────────────
-- Deux graphies du même Compagnon existaient : narrateur 8 « Abou Sa^id
--   Al-Khoudriyy » (+ savant 75) et narrateur 14 « Abou Saʿid al-Khudri »
--   (+ savant 76). Conservé : 14 / 76.
-- Opération (data, ponctuelle) :
--   update hadith_narrateurs set narrateur_id=14 where narrateur_id=8; (3 liens,
--     aucun chevauchement) → le trigger de synchro régénère hadiths.narrateur.
--   delete narrateurs id=8 ; delete savants id=75 (aucune référence).
-- Résultat : narrateur 14 porte 5 liens (hadiths 18,29,46,98,110), plus aucune
--   occurrence de l'ancienne graphie.

-- ─────────────────────────────────────────────────────────────────────────
-- Compagnons ↔ savants : lien explicite, dédoublonnage, recherche par id
-- ─────────────────────────────────────────────────────────────────────────
-- Migration narrateur_savant_link_and_dedup (+ fix_narrateur_savant_normalization) :
--   • narrateurs.savant_id (FK → savants, ON DELETE SET NULL) : lien explicite.
--   • Trigger BEFORE réécrit : rapproche par NOM NORMALISÉ (unaccent PUIS retrait
--     des séparateurs — l'ordre inverse supprimait les lettres accentuées et
--     cassait le rapprochement), en préférant une fiche historique (non
--     « Compagnon ») ; ne crée une fiche que si aucune ne correspond ; propage un
--     renommage uniquement vers une fiche Compagnon ; pose narrateurs.savant_id.
--   • Doublons de graphie fusionnés : Ibn ʿUmar (fiches 68 puis 106 → 50) et
--     ʿAli (81 → 26 « Imam ^Aliyy », lien narrateur posé à la main car nom trop
--     différent). Résultat : 0 doublon par nom normalisé.
-- Migration search_by_id_hadiths_paroles : search_hadiths / search_paroles
--   acceptent une requête purement numérique = recherche par id
--   ( or (q ~ '^[0-9]+$' and id = q::bigint) ). Côté front, les listes admin à
--   filtrage client (coran, équivoques, invocations, savants, dossiers, fiqh,
--   femmes) matchent aussi l'id exact (avec un éventuel « # » en tête).

-- ─────────────────────────────────────────────────────────────────────────
-- Page publique Savants : Compagnons distingués et hiérarchisés
-- ─────────────────────────────────────────────────────────────────────────
-- Migration savants_public_compagnons :
--   • savants.role (nullable) : rôle honorifique porté par la fiche (cas sans
--     narrateur lié, ex. Abou Bakr → calife_rachidoun). Sinon rôle déduit du
--     narrateur lié.
--   • savants_all() inclut désormais les Compagnons (même sans biographie) et
--     expose is_compagnon, role, rang (0 califes bien-guidés, 1 mères des
--     croyants, 2 autres Compagnons, 3 savants).
--   • savant_by_slug() renvoie aussi is_compagnon + role.
-- Front : /savants affiche deux sections distinctes — « Les Compagnons du
--   Prophète ﷺ » (en premier, cartes à accent or, badges Calife bien-guidé /
--   Mère des croyants / Compagnon) puis « Les Savants ». Les fiches sans
--   biographie restent accessibles.

-- ─────────────────────────────────────────────────────────────────────────
-- Admin — champ « Rôle honorifique » sur la fiche savant
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations admin_savant_role + savants_is_compagnon_role :
--   • admin_get_savant renvoie role ; admin_save_savant accepte role (validé
--     dans calife_rachidoun | epouse_prophete, sinon null).
--   • is_compagnon (savants_all / savant_by_slug) devient vrai dès qu'un role est
--     posé — un Compagnon non-narrateur apparaît ainsi pour sa biographie en
--     mettant génération « Compagnon » et/ou un rôle.
-- Front : formulaire savant, section « Repères », sélecteur Rôle honorifique
--   (— aucun / Calife bien-guidé / Mère des croyants).

-- ─────────────────────────────────────────────────────────────────────────
-- Paroles : « commente un livre » ; page équivoque : titre = thème
-- ─────────────────────────────────────────────────────────────────────────
-- Migration parole_commente_livre : colonne paroles.commente_livre (texte libre).
--   admin_get_parole / admin_save_parole / get_parole la gèrent. Front : champ
--   « Commente un livre » dans le formulaire parole ; affiché sur la fiche parole.
-- Front équivoques : l'en-tête de la fiche n'affiche plus « Le sens de … » ; le
--   titre est le thème, l'eyebrow indique « Hadith/Verset équivoque ». Cartes de
--   la liste uniformisées (thème = titre 2 lignes, arabe tronqué à 3 lignes,
--   source sur une ligne).

-- ─────────────────────────────────────────────────────────────────────────
-- Hadith ↔ fiche équivoque (présence dans les 2 rubriques)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration hadith_equivoque_link :
--   • versets_equivoques.hadith_id (FK → hadiths, ON DELETE CASCADE, unique).
--   • admin_save_hadith accepte is_equivoque : à cocher, crée/synchronise la
--     fiche équivoque liée (type hadith, textes copiés, published=false) ; à
--     décocher, supprime la fiche liée seulement si elle est vide (aucun
--     argument ni bloc). admin_get_hadith renvoie is_equivoque / equivoque_id /
--     equivoque_slug. get_hadith renvoie l'objet equivoque (slug,id) si publié.
-- Flux : on marque le hadith équivoque → il apparaît dans « Versets et hadiths
--   équivoques » où l'on saisit les arguments (blocs / sens juste / objection /
--   réponse) ; une fois la fiche publiée, la fiche publique du hadith affiche
--   l'analyse (blocs) + un lien vers l'analyse complète.

-- ─────────────────────────────────────────────────────────────────────────
-- Hadith ↔ équivoque : rattachement des existants + symétrie
-- ─────────────────────────────────────────────────────────────────────────
-- Migration backfill_equivoque_hadiths : les hadiths équivoques existants
--   (type='hadith', sans hadith_id) sont rattachés à la rubrique Hadiths — liés
--   au hadith de même texte (normalize_ar) si présent, sinon un hadith est créé
--   (sujet=theme, textes copiés, tag « équivoque ») — puis hadith_id est posé.
-- Migration equivoque_to_hadith_reverse : admin_save_verset_equivoque crée/relie
--   désormais un hadith pour tout hadith équivoque sans hadith_id (symétrie avec
--   admin_save_hadith.is_equivoque). Résultat : quel que soit le point d'entrée
--   (Hadiths ou Équivoques), le hadith équivoque apparaît dans les deux rubriques.

-- Data : tag des 5 hadiths équivoques standardisé — ajout de « équivoque » et
--   « interprétation » (fusion non destructive, tags existants conservés),
--   thèmes re-déduits.

-- Data : les 56 paroles non vides ont été enveloppées en guillemets simples
--   ‹ … › (nettoyage des guillemets/parenthèses/espaces existants en tête/fin),
--   pour uniformiser avec le gabarit de saisie. Les 2 paroles vides sont
--   laissées telles quelles.

-- ─────────────────────────────────────────────────────────────────────────
-- Guillemets simples ‹ › traités comme les autres guillemets
-- ─────────────────────────────────────────────────────────────────────────
-- Migrations normalize_simple_guillemets + normalize_ar_btrim :
--   • normalize_ar retire aussi ‹ › (U+2039/U+203A) et applique btrim →
--     « ‹ texte › » et « texte » sont identiques à la recherche (toutes rubriques).
--   • paroles.arabe_hash recréé pour ignorer ‹ › (détection de doublon
--     transparente). Index unique reconstruit (56 hachages distincts).
--   Les autres tables à arabe_hash (hadiths, coran, dhikrs, douaas) n'utilisent
--   pas ‹ › (gabarits « » ou ﴿ ﴾) → inchangées côté hash ; la recherche est
--   couverte par normalize_ar.

-- ─────────────────────────────────────────────────────────────────────────
-- Phase 6 — Exégèse des sourates : intro + lisibilité (partiel)
-- ─────────────────────────────────────────────────────────────────────────
-- Migration phase6_sourate_intro_ordre :
--   • sourates.introduction_md (nullable, Markdown) — 6.1
--   • sourates.ordre_revelation (nullable int) — 6.5
--   get_sourate / admin_get_sourate / admin_save_sourate mis à jour.
-- Front : page /coran/sourates/:slug refondue d'après la maquette validée —
--   en-tête resserré max-width + chips (révélation, ordre, nb versets) et
--   actions (6.5) ; intro masquée si vide (6.1) ; « Lire la sourate entière »
--   repliable, extrait tant que le texte complet n'est pas importé (6.4) ;
--   navigateur de versets sticky (6.4) ; exégèses en accordéon <details> (6.3).
-- Reste : 6.2 (exégèse par plage de versets) et 6.6 (import du texte coranique
--   complet — à cadrer : provenance à confirmer).

-- Phase 6.6 — Texte coranique complet (« Lire la sourate entière »)
--   Riwāyah Ḥafṣ ʿan ʿĀṣim, script ʿUthmānī, muṣḥaf de Médine.
--   Source : King Fahd Complex (qurancomplex.gov.sa), édition ara-quranuthmanihaf
--   (fawazahmed0/quran-api). Décomptes vérifiés : 6236 versets, 114 sourates.
--   Bundlé en local (public/data/quran-uthmani.json) → hors-ligne (Capacitor) ;
--   non précaché par le service worker (json hors globPatterns). Aucune table DB
--   (le texte vit côté front, découplé de l'exégèse qui reste sélective).

-- Phase 6.2 — Exégèse par plage de versets.
--   Migration phase6_exegese_plage : exegeses.verset_fin (nullable) — une exégèse
--   couvre [numéro du verset .. verset_fin]. Rétrocompatible (null = un verset).
--   get_sourate / admin_get_sourate / admin_save_sourate gèrent verset_fin.
--   Admin : champ « Jusqu'au verset (plage) » sur chaque exégèse (regroupe sans
--   re-saisir). Public : versets regroupés par plage (badge « Versets D à F »),
--   exégèses de la plage réunies sous l'accordéon.
