-- ============================================================================
-- Phase 14.6/14.7 — Citations réutilisables + « Le jugement rationnel »
-- ============================================================================

-- Citations rattachées à une page d'exposé (article, jugement rationnel…).
create table if not exists public.expose_citations (
  id bigint generated by default as identity primary key,
  expose_slug text not null,
  section integer,                 -- n° de section de la prose (null = bloc général)
  type text not null check (type in ('verset','hadith','parole')),
  ref_id bigint,                   -- hadith→hadiths.id, parole→paroles.id
  arabe text, phonetique text, signification text, ref text,
  accordeon boolean not null default false,
  ordre integer not null default 0
);
alter table public.expose_citations enable row level security;
create policy "public read" on public.expose_citations for select to public using (true);
-- RPC get_expose_citations(slug) : résout parole/hadith (arabe, signification, ref,
-- savant/generation/parole_slug, hadith_slug/id) ; verset = champs en clair.

-- 14.7 — exposé « Le jugement rationnel »
insert into public.exposes (slug, titre, contenu_md) values
  ('jugement-rationnel', 'Le jugement rationnel', '⟨prose Markdown : al-wājib, al-mustaḥīl, al-jāʾiz, la raison⟩')
on conflict (slug) do nothing;

-- ─── Recettes citations (article & jugement rationnel) ───────────────────────
-- Parole référencée (pointe vers /paroles/:slug) :
--   insert into public.expose_citations (expose_slug, section, type, ref_id, ordre)
--   select 'comprendre-textes-equivoques', 3, 'parole', p.id, 0
--   from public.paroles p where p.slug = '⟨slug-parole⟩';
-- Verset en clair :
--   insert into public.expose_citations (expose_slug, section, type, arabe, signification, ref)
--   values ('jugement-rationnel', 4, 'verset', '⟨verset arabe⟩', '⟨sens⟩', 'Sourate … : …');
-- Hadith référencé :
--   insert into public.expose_citations (expose_slug, type, ref_id) values ('jugement-rationnel','hadith', ⟨hadith_id⟩);
-- accordeon = true pour replier une preuve secondaire ; section = n° du titre ## (1..N).
