-- ============================================================================
-- Phase 14.2 — Rubrique « Récits » (Histoires des Prophètes / Vies des vertueux)
-- ============================================================================
create table if not exists public.recits (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  categorie   text not null check (categorie in ('prophetes','vertueux')),
  titre       text not null,
  contenu_md  text,
  image_url   text,
  ordre       integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists recits_categorie_ordre_idx on public.recits(categorie, ordre);

alter table public.recits enable row level security;
create policy "public read" on public.recits for select to public using (true);

-- Index (léger) + fiche.
create or replace function public.recits_all()
returns json language sql stable as $function$
  select coalesce(json_agg(row_to_json(r) order by r.categorie, r.ordre, r.titre), '[]'::json)
  from (select slug, categorie, titre, image_url, ordre from public.recits) r;
$function$;
grant execute on function public.recits_all() to anon, authenticated;

create or replace function public.get_recit(p_slug text)
returns json language sql stable as $function$
  select row_to_json(x) from (
    select slug, categorie, titre, contenu_md, image_url
    from public.recits where slug = p_slug limit 1
  ) x;
$function$;
grant execute on function public.get_recit(text) to anon, authenticated;
