-- ============================================================================
-- Phase 14.6 — « Versets et hadiths équivoques » + article de fond
-- ============================================================================

-- 14.6a — généralisation aux hadiths + index/détail
alter table public.versets_equivoques
  add column if not exists type text not null default 'verset',
  add column if not exists rapporteur text,
  add column if not exists recueil text,
  add column if not exists numero text;
alter table public.versets_equivoques
  add constraint versets_equivoques_type_check check (type in ('verset','hadith'));
-- search_versets_equivoques : param type_filter + champs type/rapporteur/recueil/numero
-- get_verset_equivoque : renvoie type + source hadith (+ parole_slug des preuves)

-- 14.6b — article « Comprendre les textes équivoques »
create table if not exists public.mutashabih_exemples (
  id bigint generated by default as identity primary key,
  mot_arabe text not null, translitteration text,
  sens_apparent text, sens_vise text, ordre integer not null default 0
);
alter table public.mutashabih_exemples enable row level security;
create policy "public read" on public.mutashabih_exemples for select to public using (true);
-- RPC mutashabih_exemples_all()

-- Bloc « texte fondateur » optionnel sur exposes
alter table public.exposes
  add column if not exists verset_arabe text, add column if not exists verset_traduction text,
  add column if not exists verset_phonetique text, add column if not exists verset_ref text;
-- exposes: slug comprendre-textes-equivoques (prose Markdown + verset_ref)

-- ─── Recettes ───────────────────────────────────────────────────────────────
-- Un HADITH équivoque : type='hadith', verset_arabe = le hadith, rapporteur/recueil/numero.
--   insert into public.versets_equivoques (slug, type, theme, verset_arabe, verset_traduction,
--     rapporteur, recueil, numero, sens_juste, published)
--   values ('slug','hadith','⟨thème⟩','⟨hadith arabe⟩','⟨traduction⟩','⟨rapporteur⟩','⟨recueil⟩','⟨n°⟩','⟨sens juste⟩', true);
-- Verset fondateur de l'article (coller l'arabe soi-même) :
--   update public.exposes set verset_arabe='⟨Āl ʿImrān 3:7 arabe⟩', verset_traduction='⟨…⟩',
--     verset_phonetique='⟨…⟩' where slug='comprendre-textes-equivoques';
-- Cartes « subtilité de la langue » :
--   insert into public.mutashabih_exemples (mot_arabe, translitteration, sens_apparent, sens_vise, ordre)
--   values ('⟨mot arabe⟩','⟨translittération⟩','⟨sens apparent⟩','⟨sens visé⟩',0);
